spring:
  application:
    name: digital-wallet-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet_db}
    username: ${SPRING_DATASOURCE_USERNAME:wallet_user}
    password: ${SPRING_DATASOURCE_PASSWORD:wallet_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  client:
  authorizer:
    url: ${AUTHORIZER_URL:https://util.devi.tools/api/v2/authorize}
  notification:
    url: ${NOTIFICATION_URL:https://util.devi.tools/api/v1/notify}
