spring:
  application:
    name: digital-wallet-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wallet_db}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

api:
  security:
    jwt:
      secret: ${JWT_SECRET:chave-secreta-padrao-desenvolvimento-local-123456}
      expiration: ${JWT_EXPIRATION:86400000}
  client:
    authorizer:
      url: ${AUTHORIZER_URL:https://util.devi.tools/api/v2/authorize}
    notification:
      url: ${NOTIFICATION_URL:https://util.devi.tools/api/v1/notify}
